### ISSUE TITLE
Review DevOps-related team agreements

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#1012]
- [x]  setup meeting with developers - week of December 12
- [x]  Create Miro board: https://miro.com/app/board/uXjVPGv__Vc=/
- [x]  Document team agreements on miro
- [x]  Setup a review call in January to loop in team members who aren't present
- [x]  Create zenhub tickets for any next steps

**Comment by LindsayMacfarlane** [comment]
Hi @pbastia - shall we wait on this ticket until we have the new contract in place?

**Comment by pbastia** [comment]
makes a lot of sense to me @LindsayMacfarlane

**Comment by Dianadec** [comment]
@dleard flagging this card based on what you said in standup - @LindsayMacfarlane I moved it into the backlog since this was still in New Issues.

**Comment by pbastia** [comment]
Created a miro board called "DevOps Team Agreements" so that we can start putting stickies and not forget lessons

**Comment by Dianadec** [comment]
@pbastia could we connect to go over a bit of an agenda for this devops team agreement session? Also, were we shortening it to 1-hour? I believe the plan was to also record it. And setup a post-session review to loop in folks who are currently/will be on vacation that day.

**Comment by Dianadec** [comment]
Next steps listed at the end of the meeting on Dec. 15:
- Arrange Openshift training (done - sent links to Sepehr, Nan and Sam)
- Add DevOps label to ZenHub Cards
- Add DevOps team agreement documentation, resources, links, and contacts to cas-home https://github.com/bcgov/cas-home
- Setup pairing on DevOps tasks/cards (ongoing)
- List Kubernetes resources to read

cc @pbastia

**Comment by Dianadec** [comment]
OpenShift Training Info
    
OpenShift 101: January 25 . Spots are available Yang, Nan 1 LWRS:EX and you can register here. - Please read the course details since it also notes additional times for labs after the session
	
OpenShift 201: January 19 - Spots are full, no waitlist, but Matt S. will contact me if there are cancellations. They've got a hard cap on numbers, as they re-use the same 20 project sets and related licenses for 201. The next dates will be announced at the next PS Meetup on Jan 17. Most likely, the dates for the next 201 training will be February 14th and 15th.
