### ISSUE TITLE
Confirm the math of the 'Holdback Payment Amount' field

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1121]
#### Describe the task

During Emission Intensity Reports Usability testing, Devin indicated that the math may not be aligned for the Holdback Payment Amount. He also wanted to know how we calculated the amounts, and indicated that they were working on a formula that would be approved around November. This would be easier to implement than the lookup table under Schedule G of Funding Agreements.

This ticket's scope covers exploring the math for the this field with developers and Tech Team, as well as ensuring the formula is communicated to the DS team for implementation.

#### Additional context

- This is a great chance to r**evisit the ALL the calculated fields and confirm the formula and conditions**, since they are all interrelated.

#### Acceptance Criteria

- [x] Schedule and conduct input gathering sessions with CIF
- [x] Confirm and document formula for the calculations with examples and sample data for test/validation purposes
- [x] Sync with the team and create tickets for implementation

**Comment by suhafa** [comment]
@nanyangpro added in another exploration ticket as discussed as part of handoff

**Comment by LindsayMacfarlane** [comment]
@nanyangpro - would this be confirming with the CIF team? What is your recommended priority for this ticket? Can the work be lumped with any upcoming usability sessions?

**Comment by pbastia** [comment]
The current calculation method is based on Schedule G's table from the funding agreements.
> the math may not be aligned for the Holdback Payment Amount.
Could we have an example of a calculation where it's not aligned?

We can probably hold off until we have an updated calculation formula

**Comment by Dianadec** [comment]
Next steps: reach out to tech/ops team to see where they are at with the formula. 
Question for team: Does this need a meeting? Yes. Prior to that Nan will reach out to Pierre.

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket is ready for you to review and can be closed with summary documented below. Please feel free to let me know if you have questions.

- All fields regarding calculations were revisited since they are interrelated. [Detailed formula with examples](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EcXm1DnetBZNgFOkakDR_IEB1RS8r51PTHqH2h4C5L6URw?e=RbiNV2) for ALL of them were reviewed by the CIF team and synced up with the developers.
- 3 forms are impacted referring to the [confirmed formula](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EcXm1DnetBZNgFOkakDR_IEB1RS8r51PTHqH2h4C5L6URw?e=RbiNV2) above:
  - Budgets, Expenses, & Payments (#717, #944, #984 updated as discussed with @dleard)
  - Milestone Reports (#986 updated as discussed with @dleard)
  - Emissions Intensity Reports (#1210 created for refinements)

**Comment by LindsayMacfarlane** [comment]
Thank you @nanyangpro!
