### ISSUE TITLE
Log in message

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1195]
#### Describe the task

Design/create log in message for when a user logs into the CIF app, but doesn't have any roles assigned. In this scenario, when a user logs in, they will see a blank screen and not know/understand why. Providing a welcome message with instructions on who to contact would help improve user experience. 

#### Acceptance Criteria

- [x] Draft message
- [x] Create Figma Design
- [x] Review and get input from dev team and CIF team

#### Additional context

- Relates to user story #1172

#### Finalized wireframe
[Figma Link](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=6391%3A302&t=LQhnU1Qn7tevySM4-1)

**Comment by suhafa** [comment]
[Proposed design](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=6391%3A302&t=1R2RngQqwRHtLEFi-1) to be reviewed at Sprint Review with CIF team and in stand up with Scrum. 

Once reviewed, this ticket can be closed c:

**Comment by suhafa** [comment]
Taggin @pbastia for your review of the [proposed design](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=6391%3A302&t=ahpOy2GkUpkDl440-1) as well

**Comment by LindsayMacfarlane** [comment]
Looks great @suhafa! Something for consideration and input from @pbastia - given we are headed towards external access for users who will need a BCeID - should we design with that in mind? If so, should we consider adding in a reference to BCeID and remove a reference to the CIF internal users channel? OR can this be coded in a way that if a user has a BCeID they will get one message...and if a user has IDIR they would get another message?

**Comment by pbastia** [comment]
This looks great to me! I think if it's external facing, we may want something a tad more formal than `Hi there!`. This will have to be vetted by the business area anyways, the wording can be easily tweaked.

For the external flow @LindsayMacfarlane, I think this will have to be a separate page, mostly because there are questions to answer:
- Do we allow anyone (with a BCeID) to submit an application, on behalf of any organisation? If the organisation is a free form - like it is right now in the document-based application - we'll have to handle the case of multiple spellings (ie Pulp and paper Inc. vs Pulp and paper Ltd. vs Pulp and pater Limited)
- Do we vet people and grant them access to one or more organisations, similarly to CIIP? (which means we will have to maintain a list of allowed organisations, and allow a separate flow for when the organisation doesn't exist)
- Are the external intake and program management entirely different applications when we deploy the MVP for that functionality?

**Comment by LindsayMacfarlane** [comment]
No significant feedback from CIF team during Sprint Review. Received some thumbs up during the demo. 

FYI: @suhafa

**Comment by suhafa** [comment]
Thank you @LindsayMacfarlane @pbastia those are some excellent points! (sorry I had missed out on these prior to presenting in today's demo) I am not too familiar with the workings of BCeID so am wondering if we need to factor that in the scope of _this_ ticket or it needs another design ticket if the workflows don't intersect. What do you say? I'll be getting rid of the `'Hi there!'` regardless xD

**Comment by LindsayMacfarlane** [comment]
@suhafa - I think we are good to proceed with what you have designed and we can address the BCeID stuff through other work/tickets. For the internal user part, I like the Hi there! (makes it seem more friendly and welcoming), but the team can override me on that ;)

**Comment by suhafa** [comment]
@LindsayMacfarlane in that case, the Hi there! stays ;D Will update this ticket with finalized wireframe.

**Comment by LindsayMacfarlane** [comment]
@suhafa - thank you so much!
