### ISSUE TITLE
Usability testing of Amendments and Revisions

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1275]
#### Describe the task

Plan and execute usability testing session for amendments and revisions. 

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by LindsayMacfarlane** [comment]
FYI @nanyangpro and @suhafa - I've created this ticket to help us plan and complete usability testing related to the amendments and revisions workflow/features.

**Comment by nanyangpro** [comment]
Wonderful, thanks @LindsayMacfarlane! I'll refine it with further details as soon as I can.

**Comment by mikevespi** [comment]
Changes are being made to the prototype that will change the flow. A dev/design sync will be had likely this week, and this can be pushed to after that meeting takes place.

Depending on how significant the changes are, it may be better to walk through the new prototypes for the first walkthrough, rather than waiting for it to be built.

**Comment by Dianadec** [comment]
Closing this card due to the duplicate 1422. @nanyangpro fyi @LindsayMacfarlane
