### ISSUE TITLE
createUserFromSession is sometime done as a cif_guest

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#195]
Describe the Bug:

looks like it happens when logging in from the `login-redirect` page, and leads to the user being eventually redirected to the dashboard instead of the requested page

Probability (1-5): 2

Effect (1-5): 2

Steps to reproduce the behaviour:

- bug observed in local development environment

**Comment by pbastia** [comment]
could it be because our sso middleware is an [async function](https://github.com/bcgov/cas-cif/blob/82eea6528057e39016832e8531ab5e797e3c4f93/app/server/middleware/sso.ts#L16) (not sure why?) that we then [need to await](https://github.com/bcgov/cas-cif/blob/82eea6528057e39016832e8531ab5e797e3c4f93/app/server/index.ts#L49)? I'm wondering if doing this still wraps the sso middleware in a promise that is not awaited by express, and we have a very short race condition with the next call to `/auth-callback`

**Comment by matthieu-foucault** [comment]
I think the race condition is tied to when the session data is persisted. We rely on the `sid` cookie to retrieve the JWT claims, but those may not be saved in the database by the time the request to `/graphql` is handled.

**Comment by matthieu-foucault** [comment]
See https://www.graphile.org/postgraphile/usage-schema/
