### ISSUE TITLE
As a CIF user, I want to view a project details, so that I can, at a glance, view high level information about the project

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#203]
#### Description:
As a CIF user, I want to view a project details, so that I can, at a glance, view high level information about the project.

#### Acceptance Criteria:
Given that I navigate to the `/cif/project/<projectRelayId>` page
When the page loads
Then I can see a project's information

#### Development Checklist:
- [ ] The project page loads data from the `project`, `project_contact`, `project_manager`, etc, tables, instead of the `form_change` table
- [ ] Design should remain minimalist (e.g. see https://design-system.service.gov.uk/components/summary-list/) and will be revised after v1
- [ ] Meets the DOD

#### Notes:
- UX questions: do we want a single page or tabs? This could be updated easily if we make components for the different sections

Personas
[Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)

[Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

[Tech Team ](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by LindsayMacfarlane** [comment]
Backlog refinement (January 11): this ticket needs further discussion. A dedicated meeting should be set up for team to discuss).

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/203?planning-poker) with ZenHub @AlexZorkin @dleard @pbastia

**Comment by BCerki** [comment]
@matthieu-foucault, I have a few questions on this one:

1. 
> * The project page loads data from the `project`, `project_contact`, `project_manager`, etc, tables
What data should be shown?

2. 

> * UX questions: do we want a single page or tabs? This could be updated easily if we make components for the different sections
Do we have an answer to this question yet? And as far as making components, tying into the above question, what are the sections?

3. I don't have access to the links under personas

**Comment by matthieu-foucault** [comment]
1. @suhafa is currently working on making an inventory of all of the data that we will need to collect, so that's something we're still figuring out, but it would be good to have all of the values that are displayed in the project creation form, for consistency. It doesn't have to be all added at once though (especially for the managers, @dleard is currently finalizing a PR that updates that.
2. For now let's keep this as simple as possible code-wise, even if it's not the best UX. I'd use a definition list (see the contact view page for an example) 
3. Me neither, maybe @Sriram-pc can look into that

**Comment by Sriram-pc** [comment]
3) @BCerki. Please try going into the CIF Internal Users channel and try opening the below mentioned location. Unfortunately many of those links are going to Sharepoint instead of MS teams and contractors are not having access sometimes.
![image.png](https://images.zenhubusercontent.com/6149103e0c14630f5a9c158a/f94deac2-369b-4a94-853b-7e71c8ea6c45)

**Comment by Sriram-pc** [comment]
Also I tried to change the access setting for these personas. Please try now from the link

**Comment by BCerki** [comment]
> Also I tried to change the access setting for these personas. Please try now from the link

@Sriram-pc I still can't access the files from the link here, but via Teams works fine. Thanks!

**Comment by LindsayMacfarlane** [comment]
Thanks @BCerki ! 

Tested in dev:
- reviewed an existing project
- added a new project and then viewed project page

Some observations for future design consideration (FYI @suhafa):
-  page alignment
- May want to add $ for the funding requesting field
- Project Manager - ability to distinguish between the roles and whether primary/secondary (currently lists names)
