### ISSUE TITLE
As a CIF user, I want to see an error message when an unhandled error happens on the front-end, so that I know what to do

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#310]
#### Description:

Brief description of the work involved, including any user research context or key decisions.

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

#### Notes:

-

**Comment by matthieu-foucault** [comment]
@pbastia is this handled by #223?

**Comment by pbastia** [comment]
@matthieu-foucault  I don't think so, if I remember right this is about graphql errors not being caught (since postgraphile still returns a 200 code, just a different payload). And relay silently ignoring this if the `onError` field is not set in the mutation call.

We should have a default `onError` that captures the error with `Sentry.captureException(...)`

**Comment by matthieu-foucault** [comment]
This issue is strictly about front-end exception. #309 is the one about Graphql errors.

**Comment by pbastia** [comment]
Oh I see! In that case #223 will display the 500 page content when a frontend error happens. Maybe it's worth a quick UX check with @suhafa @elliottSlee to make sure this is appropriate?

**Comment by matthieu-foucault** [comment]
I don't think that the user needs, or would understand, a different page for front- vs back-end errors. Closing this :)
