### ISSUE TITLE
Discovery and user research on emissions intensity report

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#400]
#### Describe the task

Complete user research related to emissions intensity and how it can be included in the CIF app. 

#### Acceptance Criteria

- [x] Identify necessary documents & spreadsheets
- [x] compile information onto Miro
- [x] Identify questions related to emissions intensity report
- [x] Book meeting with Taylor and CIF team
- [x] Identify fields/information that should be included in [Appendix A pt 2 Miro board](https://miro.com/app/board/uXjVOD--YAU=/?moveToWidget=3458764521470992518&cot=14)
- [x] Identify dependencies

#### Additional context

-

**Comment by elliottSlee** [comment]
@nanyangpro & @suhafa can we drop all the existing documents here in the github issue so that it's all in one place?

[Project tracking spreadsheets](https://bcgov.sharepoint.com/:x:/r/teams/00608-CIFInternalUsers/Shared%20Documents/CIF%20Internal%20Users/CIF%20Reference%20Documents/CIF%20Operations/2020%20-%20Project%20Tracking%20-%20Reports.xlsx?d=w9282f1b52da34ef590d24191db03df42&csf=1&web=1&e=btGPNq) have the TEIMP start & end dates.
The [Funding Agreement - Schedule E on p. 41](https://bcgov.sharepoint.com/:b:/r/teams/00608-CIFInternalUsers/Shared%20Documents/CIF%20Internal%20Users/CIF%20Reference%20Documents/Funding%20Agreement%20Negotiations/2.%20RFP-EP-2021_Apx_A_Funding%20Agreement.pdf?csf=1&web=1&e=gtfvvb) has more including baseline.

**Comment by elliottSlee** [comment]
Discovery findings are found: 
- [Emissions Performance Process Map on the Miro board, CIF Process](https://miro.com/app/board/o9J_lwRsVsQ=/?moveToWidget=3458764526298213660&cot=14)
- [User Stories on Figma](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=1703%3A2665)

**Comment by nanyangpro** [comment]
Wonderful, thanks @elliottSlee!

**Comment by suhafa** [comment]
All ground work done post review with Taylor for the initial wireframes. Closing this @LindsayMacfarlane

**Comment by nanyangpro** [comment]
Thanks @suhafa for leading it. (FYI, I'm still on this ticket reviewing the findings and may have questions upon further clarifications.)
