### ISSUE TITLE
As a CIF user, I want to download a file attached to a project, so I can read it or retrieve information from it

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#476]
#### Description:

Downloading a single file attached to a project.

#### Acceptance Criteria:

Given I am a CIF user.
When I view the project's attachments
Then I can see a Download button for each file

Given I am a CIF user
When I view the projects' attachments
And I click on the Download button for an attachment
Then the file is downloaded with the proper name and extension, and the browser knows how large the file is

#### Development Checklist:

- [x] Python API: retrieves the file from minio and offers an endpoint to download the file
- [x] CIF server: retrieves the file name and size from the database
- [x] CIF server: retrieves the file from minio and streams that back to the user through a dedicated express endpoint
- [ ] Meets the DOD

#### Notes:

-

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/476?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Thanks for your work on getting document management more functional @pbastia! Much appreciated. 

Observations:
- The download a document brought me to a table where a user can upload or download an attachment. Should we have a ticket that makes this page accessible through the dashboard? Otherwise it is a hard to find.  
- What file types do we accept? Can .jpg be uploaded or have we restricted the file type? 
- When uploading an attachment, how do we associate it to a particular project. It also wasn't super clear how to find an uploaded document.

**Comment by LindsayMacfarlane** [comment]
@pbastia - thank you for explaining where things are at in relation to document management during our check-in.
