### ISSUE TITLE
Observation and support for CIF Ops Team during soft launch

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#555]
#### Describe the task

During soft launch, schedule time with Amanda to observe data entry and user experience. 

#### Acceptance Criteria
- [x] Schedule time with Amanda
- [x] Document observation/feedback
- [x] Report out to team
- [x] Research onboarding best practices
- Have internal brainstorm session as to how we want to onboard the team and how we can support them best (documentation? walkthrough? training? Refer #550) 
- Discuss how we want to do user research in their initial usage of the application

**Comment by LindsayMacfarlane** [comment]
FYI @nanyangpro

**Comment by nanyangpro** [comment]
Thanks @LindsayMacfarlane!

Notes to self: see comments in #550.

**Comment by matthieu-foucault** [comment]
@nanyangpro  check out the "CIIP Web App Training - June 2021" miro board, we can probably reuse that template

**Comment by nanyangpro** [comment]
Good suggestion, thanks @matthieu-foucault!

**Comment by nanyangpro** [comment]
3 Amigos meeting with Taylor and Amanda: Including the amendments aspect of things in the training.

**Comment by LindsayMacfarlane** [comment]
@nanyangpro and @suhafa - can you please review and update acceptance criteria.

**Comment by nanyangpro** [comment]
In-person observation session in TEST with Amanda on Jul 11, 2020 [Notes](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EQ2lb_LBktJMv1VTff2fBYsBSLWFMfSD8NFzNzXOGzGzsw?e=KFhzPT) linked.

**Action items** from the session (not blockers for releasing to PROD):
(Feel free to add any missing ones for the record, @LindsayMacfarlane & @suhafa )
- Create a ticket for relocating the "Add New Report" button on the Milestone/Quarterly/Annual Report forms to the bottom instead of the top
- Create a ticket for relabeling the "Summary" field on the to "Project Description"
- Refine #593 to reflect the appropriate dependency on the date calculation ("Substantial Completion Date is entered, and "Report Due Date" is populated based on it)
- Refine #579 to allow manual sorting or auto-reordering (chronologically) of reports
- Create a bug ticket for the "should be a string" bug

**Comment by suhafa** [comment]
Great summation @nanyangpro a few more action items I would like to add:
- Contact emails should be a hyperlink (mailto function) when viewing the project contacts so that it opens an email in Outlook for CIF team (a temporary solution before we add communication in the app)
- Add commas/dollar signs for the amounts  (eg. maximum amount, total eligible expenses) when reviewing the project before submission.
- Ability to copy-paste date into the dates field would be nice
- Validation error remained in the fields even if correct information was entered. Its a bug which can be misleading

**Comment by suhafa** [comment]
Hi @LindsayMacfarlane, created tickets #843, #844, # #845, #846 on the basis of our notes here.  Only the following have yet to have tickets, but I'd want to confirm with the dev team if we already have them captured or if its feasible:
- "Ability to copy-paste date into the dates field would be nice
- Validation error remained in the fields even if correct information was entered. Its a bug which can be misleading"

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro and @suhafa - how are we feeling about this ticket? Are we ready to close it? The issue of onboarding was brought up in standup this morning. I know Amanda feels pretty comfortable with the system, so how do we want to approach onboarding? Do we want to make sure the team is on stand-by and available to support her next week? Dylan also recommended that we have Amanda enter another couple of records in TEST before entering data into PROD. It was also thought that having them enter all the contact information first might be helpful and help with streamlining some of their workflow.

**Comment by nanyangpro** [comment]
Good questions, @LindsayMacfarlane - I like @dleard 's suggestion, this would help CIF Ops, especially Amanda to figure out what would be the most efficient approach, and also allow us a few more observation sessions if necessary. If you and @suhafa like, I can send a follow-up email to Amanda post your soft launch announcement email. I'll also suggest Amanda to drop the issues/questions she encounters in our MS Teams channel, so the team can address/answer asap.

In terms of this ticket, shall we keep it open as more support may be expected from us?
