### ISSUE TITLE
As a cif user, I want to see the list of existing projects, so that I can find a project of interest

### ISSUE THREAD

**Issue by Sriram-pc** [bcgov/cas-cif#63]
### Description:
As a project coordinator, I want to be able to see the list of existing projects, so that I can find a project of interest.
The table filtering, sorting and pagination will be added in #64
The table components developed for CIIP should be reused (and adapted to move away from bootstrap)

### Acceptance Criteria:

Given that I am logged in as a `cif_internal` or `cif_admin` user,
When I go to the `/cif/projects` page
Then I see a table displaying the existing projects

Given that a project was created
When it is displayed in the projects table
Then I can see the following project information:

- Project Name
- Project Operator's trade name
- Project RFP Id
- Project Status
- List of assigned project managers (`<lastName>, <firstName>` with each manager on a separate line)
- Total Funding Request
- A button to view the project

Given that a project is displayed in the table
When I click on the button to view the project
Then I am redirected to a `/cif/project/[projectRelayId]` page

Given that a project is displayed in the table
When the project name, trade name, or project manager length exceeds Xpx (tbd)
Then it should wrap on a new line

Given that a project is displayed in the table
When the project status is displayed
Then it should have a fixed width

### Development Checklist:
- [x] Meets the DOD

#### Personas:
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)
- [Tech Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

#### Notes:

**Comment by rajpersram** [comment]
Current wireframe before CIF feedback:
![CIF Workflow Co-Design - Existing Projects List.jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/07a51167-7b6d-4f72-9131-42ff113e3e80)

**Comment by rajpersram** [comment]
Wireframe after CIF feedback:
![CIF Workflow Co-Design - Existing Projects List (3).jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/bad945a0-c060-41ad-956e-9b2d43d87f2d)

**Notes:**

- **Top Right:** User's logged in name from GAL with dropdown to Log out. Later versions perhaps could have a profile and preferences selection (TBD)

- **Bootstrap messaging** above the list title, for system alerts. Potential use later on for user status messages (TBD).

- **Trade Name:** Is an alias that the user can assign to the often much longer Legal Name Proponent.

- **RFP ID:** Using same format as what CIF is currently using. Ideally, it could be less cryptic (ie. substituting 'EP' instead of '02' for the Stream. Seeing two letters for the Type would be useful as well).

- **Status**: Bootstrap pill-badge. Options: In Progress, Measurement, Changes Requested. Options awaiting verification from CIF users.

- **Assigned**: MVP is to show all name assigned. Future versions are hoping for showing just the items the logged in user is assigned to (Matthieu suggested a URL with applied filters could be bookmarked by users to jump to a filtered list)

- **View Attachment:** Jumps to the Project Details > Attachments tab. A request was for a list of attachments that are sortable by date and kind.

- **View Notes:** Jumps to the Project Details > Notes tab. MVP is that notes from emails and phone call outcomes requested to be recorded with a flag option to show on CIF Projects List so others will know to check the notes. Any user can remove the flag, signifying the issue has been dealt with. Nice to haves later on TBD.

- **Next Report Due:** YYYY-MM-DD (Type). Each project has quarterly, annual and milestone dates. Request was for showing the next soonest date and its type. 

- **Actions:** Apply for actioning all filters. View for showing Default tab of a Project's details. Tabs still TBD from next co-design session.

- **Bottom of table on left:** Pager to show number of items per page (10, 20 [default], 50, All).

- **Footer links** TBD. Taken from CIIP for now.

- **Bottom Right:** Help link similar to CIIP to redirect users to help documentation or contact CAS or GGIRCS team as appropriate.

**Comment by rajpersram** [comment]
I think we should also add a dropdown above the table to select the Reporting Year, as we have in CIIP. If devs are in agreement, I'll update the wireframe above to reflect that.

**Comment by rajpersram** [comment]
![Project List.png](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/b3a5316a-c1f1-46f6-87b1-5972a36e076f)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/63?planning-poker) with ZenHub @dleard @pbastia

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket
[Program Development Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

[Tech Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by LindsayMacfarlane** [comment]
Thank you @matthieu-foucault ! This project lists looks great! I have a couple of questions:

- Assigned To: is this the same as Project Manager or something different? When I created a new project and assigned a project manager, the "assigned to" displayed the J. Doeloremipsum, J. Doe".
- Next Report Due: I don't believe we have this field accounted for in v1 for project creation (it doesn't look like it is in the wireframe either)?

**Comment by matthieu-foucault** [comment]
- Assigned To: Given that we will be updating the managers form soon, I opted to just hardcoding a value in the meantime. This will have to be fixed in #133, and could be renamed to "Project Managers"
- Next Report Due: We can definitely remove that column given that we won't have that information in v1
