### ISSUE TITLE
Explore next set of CIF priorities

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#708]
#### Describe the task

Start exploring and having conversations with CIF team to identify the next set of priorities for implementation. 

#### Acceptance Criteria

- [x] Review [priorities document](https://miro.com/app/board/o9J_ll12Cvk=/)
- [x] Talk to Taylor
- [x] Get list of 'other data' and relevant tracking sheets from Taylor
- [x] Discuss with Ops Team and Tech Team
- [x] Document feedback

#### Additional context
- [ ] Create required EPICS or tickets for further work as necessary
- [x] Confirm on the priority of Amendments.
- Relates to ticket #578 - project location information (note: not everything listed in ticket is actually project location info)
- Relates to ticket #205 - capturing project evaluation score

**Comment by LindsayMacfarlane** [comment]
Hi @suhafa and @nanyangpro - this ticket captures the need for discussions with CIF on what the next set of priorities are in terms of development. Feel free to refine and update the checklist.

**Comment by suhafa** [comment]
@nanyangpro see this [Miro board](https://miro.com/app/board/o9J_ll12Cvk=/), the frame 'Refined Priorities' to be specific

**Comment by nanyangpro** [comment]
Perfect, thanks @suhafa!

**Comment by nanyangpro** [comment]
Next steps suggested from the initial discussion @LindsayMacfarlane had with Taylor (office hour on Jun 8, Wednesday):
- Tech team's perspectives on TEIMP related fields
- Tech team's perspectives on other information that they want to include
- How amendment processes fit in
- Etc.

**Comment by suhafa** [comment]
@nanyangpro @LindsayMacfarlane – for the Tech team's perspectives on TEIMP, I am wondering if we want to factor in Tech Team user stories (8 in total as of now) in Figma to meet their needs in the wireframe and then confirm it with them in a discovery/user-testing session?

**Comment by nanyangpro** [comment]
Thanks @suhafa - To my understanding, it is part of the plan. We should confirm on when the tech team would be available again first.

**Comment by nanyangpro** [comment]
Updates:
- Taylor is looking to provide us the list of "other data" and relevant tracking sheet by the end of Friday, Jun 17th.
- Meeting with both Ops and Tech team has been scheduled on Tuesday, Jun 22nd. Thanks @LindsayMacfarlane!
- I'll review Taylor's document as soon as it's received, and get prepared for the discussion.

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket can be closed with summarized notes from discussions below.

**Next set of priorities:**
1. **Emissions Intensity Report related fields** (In progress)
- Relevant to Ops/Tech
2. **Pending/settled amendments** (In discovery)
- Relevant to Ops
3. **Fields in Taylor’s spreadsheet**
- Relevant to Development/Ops/Tech
- Data fields that can be handled directly through Metabase have been marked out
4. **Form enhancements (UX)**
5. **External industry-facing portal**
- Relevant to Ops
- Higher priority for the communications aspect
6. **Program-level budgets** 
- Relevant to Development/Ops
- May be handled in Metabase
7. **Document management** 
- Relevant to Ops
- Lower priority
- LAN works fine for now, main pain point lies in tracking

**Taylor's comment:**
_I think this reflects the priorities we’ve discussed to date.  To me it makes sense that our next move would be to get the rest of the data we’re currently tracking in spreadsheets into the system so that all of our data is in one place and we resolve the data inconsistency issues we’ve had in the past.  I think for the time being it makes sense for us to continue tracking the values posted on the website in a separate spreadsheet since these values don’t change often._

**Comment by LindsayMacfarlane** [comment]
Thank you @nanyangpro! I look forward to the next steps related to CIF priorities.
