### ISSUE TITLE
As an Ops Team Member, I want to see the expenses and payments to date on the Budgets, Expenses & Payments form

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#717]
#### Description:
[Formula with examples](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EcXm1DnetBZNgFOkakDR_IEB1RS8r51PTHqH2h4C5L6URw?e=RbiNV2) - Please open it with the Word app instead of browser for formatting and better readability.

[Updated design](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=2898%3A2863&t=0b38GJFZh0GzOQrz-1) in Figma

Display calculated percentage, so that the user is alerted when it's below certain threshold.
- **Proponent's Share Percentage (calculated)** (Warning: it should be NO LESS than 25%. For 2021 projects, 10% instead.)

Display calculated amounts under the **Expenses and Payments Tracker** section.
- **Total Eligible Expenses To Date (calculated)** 
- **Total Gross Payment Amount To Date (calculated)** 
- **Total Holdback Payment Amount To Date (calculated)** 
- **Total Net Payment Amount To Date (calculated)** 

The calculated values for {total_eligible_expenses_to_date, gross_payment_amount_to_date, net_payment_amount_to_date} are taken care of via computed columns in #986.

#### Acceptance Criteria:

Given I am a CIF administrator
When I create or edit a project
And I click on the "Budgets, Expenses and Payments" section in the tasklist
Then I can see a tracker section
And its title is "Expenses and Payments Tracker"

Given I am a CIF administrator
When I am on the "Budgets, Expenses and Payments" form of a project
Then I can see the following amounts and percentage calculated:
- Total Eligible Expenses To Date (calculated)
- Total Gross Payment Amount To Date (calculated)
- Total Holdback Amount To Date (calculated)
- Total Net Payment Amount To Date (calculated)
- Proponent's Share Percentage (calculated) <- this can be done on the front end, it's just Proponent Cost / Total Project Value (implemented in #942)

#### Development Checklist:

- [x] add a new jsonSchemaForm to display the calculated values. This form can be stored on the front-end as it does not have data that needs to be persisted (does not need to go in the `schema/data/prod/jsonSchemaForm` directory.
- [x] display the calculated values at the bottom of the budgets, expenses and payments page as shown in figma
- [ ] Meets the DOD

#### Notes:

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by nanyangpro** [comment]
The devs suggested implement this ticket post soft launch, thus replaced the "High Priority" label with "Medium Priority", please confirm on the priority @LindsayMacfarlane.

**Comment by nanyangpro** [comment]
The devs suggested implement this ticket post soft launch, thus replaced the "High Priority" label with "Medium Priority", please confirm on the priority @LindsayMacfarlane.

**Comment by LindsayMacfarlane** [comment]
@nanyangpro - I support moving to post soft launch.

**Comment by nanyangpro** [comment]
Perfect, thanks @LindsayMacfarlane!

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/717?planning-poker) with ZenHub @dleard @gurjmatharu @mikevespi @Sepehr-Sobhani

**Comment by nanyangpro** [comment]
Hi @pbastia, @mikevespi - As discussed in the 3 Amigos session (Aug 10) with you and Amanda, the design has been refined with the updated link and description for this ticket.

**Comment by dleard** [comment]
@nanyangpro I have some questions about this card. Let's sync on this when you have a chance.

**Comment by dleard** [comment]
On the Budgets Page:
calculated_to_date values are from completed milestones (completed if there is a value in adjusted or calculated -> total_eligible_expenses is populated)

**Comment by dleard** [comment]
Remove the Actual Province's share % field & replace with Proponent's Share % (calculation in calculations word document)

**Comment by nanyangpro** [comment]
FYI @dleard - Design (link in description) is updated according to the Formula with examples (link in description).

**Comment by gurjmatharu** [comment]
## New Project
During a new project or when the project is in its first revision the calculated values are not there.  
- Should we show any value(s) there?

## Calculated Fields
Should these calculated fields be `Readonly`? If not it's difficult to tell if these have been `adjusted`/`overwritten` or if they are true `calculated` values

## Testing
I think we need to revaluate how we're testing and base them off of the following user stories.
As a cif user I want to create a new project
As a cif user I want to view an existing project
As a cif user I want to edit an existing project & revision.

Right now we with my current approach I have the following situation.

Because we don't have `form_changes` persisting when we go to view the project we are missing the `Expenses and Payments Tracker` info:
![Screen Shot 2022-12-16 at 2.52.06 PM.png](https://images.zenhubusercontent.com/620bf57daa1ab92954017ec6/4537275f-ba65-4438-b8e9-cbc07118257c)

Additionally this also means that the data is filled in once we do the following steps.
1. create a new project/revision
1. submit the revision
1. go to `view/edit` and then navigate to budgets and expenses
1. click edit
1. now the data will be populated and you are free to continue the flow

We can either amend this card and continue fixes or create additional cards to address these issues.

**Comment by BCerki** [comment]
To address Gurjeet's notes/questions above:
- With the `CalculatedValueWidget`, the values will be read-only and if they don't have a value, we can display nothing or a message (e.g., like the rank widget: 
![image](https://user-images.githubusercontent.com/77306764/210086513-7d2c4a0c-87fe-4e6a-9a8b-c4a088fc0dae.png)
) @nanyangpro, @suhafa, what would you like to show?
- addressed the lack of persistence by using the `CalculatedValueWidget` and `formContext` rather than `form_changes`

**Comment by BCerki** [comment]
@nanyangpro, a couple more questions/notes:
- would like to confirm the proponent's share percentage calculation: Proponent Cost / Total Project Value * 100 (*100 isn't in the word doc) 
- calculated values can't be displayed in summary diffs yet (ticket [here](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1231), so since the entire tracker form is calculated, I just hid it on the diffs page. Does that work for you?

**Comment by nanyangpro** [comment]
@gurjmatharu - Thanks for your questions, please see **answers in bold** below.

## New Project
During a new project or when the project is in its first revision the calculated values are not there.  
- Should we show any value(s) there? **No.**

## Calculated Fields
- Should these calculated fields be `Readonly`? If not it's difficult to tell if these have been `adjusted`/`overwritten` or if they are true `calculated` values **Yes, read-only. Users can't update Calculated Fields, but their values may be updated as a result of changing the fields used as parameters for their calculations.**

## Testing
- cc: @pbastia

**Comment by nanyangpro** [comment]
Good questions, @BCerki. Please see my **answers in bold** below.
- **For the Calculated Fields without a value, for now, let's display a generic message "This field cannot be calculated due to lack of information now.". For future enhancements, we can tailor the messages for each field informing what information is required for the calculation.**
- would like to confirm the proponent's share percentage calculation: Proponent Cost / Total Project Value * 100 (*100 isn't in the word doc) **Please refer to what's in the word doc, notice that the format of "Province's Share Percentage" and "Proponent's Share Percentage" should be consistent.**
- calculated values can't be displayed in summary diffs yet (ticket [here](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1231)). Since the entire tracker form is calculated, I hid the whole thing on the diffs summary page. Does that work for you? **Yes, for now. (Any suggestions in terms of how to test them from front-end then?)**
- in the issue description there's text about alerts and warnings. There's nothing about that in the AC, so I assumed it was context/background info, but wanted to flag in case it's supposed to be a feature and we need a card for it **Yes, it's context information.**

**Comment by BCerki** [comment]
> * **For the Calculated Fields without a value, for now, let's display a generic message "This field cannot be calculated due to lack of information now.". For future enhancements, we can tailor the messages for each field informing what information is required for the calculation.**

Sounds good, it's easy to change the message

> * would like to confirm the proponent's share percentage calculation: Proponent Cost / Total Project Value * 100 (*100 isn't in the word doc) **Please refer to what's in the word doc, notice that the format of "Province's Share Percentage" and "Proponent's Share Percentage" should be consistent.**

Province's Share Percentage is entered as a percentage, e.g. 50%. Proponent Cost / Total Project Value is a calculation, so it's always going to give a decimal value since total is always more than proponent cost (e.g. 25/100=0.25).  So we should show 0.25, or multiply by 100 to get 25%?

> * calculated values can't be displayed in summary diffs yet (ticket [here](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1231)). Since the entire tracker form is calculated, I hid the whole thing on the diffs summary page. Does that work for you? **Yes, for now. (Any suggestions in terms of how to test them from front-end then?)**

The new fields appear on the `Budgets, Expenses & Payments` edit and view pages so we can look there for manual testing. The only place they won't show up is on the `Review and Submit` page (the page where the changes are highlighted green and yellow). Happy to give you a demo if it would be helpful.

**Comment by BCerki** [comment]
As discussed with @nanyangpro, Proponent Cost / Total Project Value*100 to get the value in percent

**Comment by mikevespi** [comment]
@nanyangpro In the calculations document, the wording is:
`Province’s Share Percentage: 50% 
Typically, 50% at most, case by case `

Does this mean that if the value of `Proponent Cost / Total Project Value*100` is greater than 50%, then the calculated value here should display 50%?

**Comment by nanyangpro** [comment]
Good question, @mikevespi. Thanks! - No, it should display the value filled by the CIF team. It's contextual information.

**Comment by mikevespi** [comment]
Thank you @nanyangpro ! I realize what happened, I was reading the provincial and proponent fields as the same XD

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki and @gurjmatharu! Overall, looks great. I couldn't seem to auto populate the Total Eligible Expenses to Date. Based on the calculation worksheet, this field should be auto-populated once all the milestone reports are completed.  I'm pretty certain this is user error, but it would be good to get another pair of eyes on it.

![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/c151dad4-97bc-4d38-ac10-c0de4eb5b593)

**Comment by LindsayMacfarlane** [comment]
Following up on my previous testing - was totally user error and I was able to figure out while testing in the TEST environment.
