### ISSUE TITLE
Bug: Empty secondary contacts result in a 'DISPLAY ERROR' on the project submission page [5]

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#830]
Describe the Bug:

Adding an empty secondary contact to a project:
- doesn't prevent from submitting the contacts form, 
- will prevent from submitting a project revision, 
- 'DISPLAY ERROR' will show up on the summary page

Probability (how likely the bug is to happen, scored from 1-5): 2

Effect (how bad the bug is when it does happen, scored from 1-5): 3

Steps to reproduce the behaviour:
1. Create or edit a project
2. Go to the contacts page, add an empty contact row, submit the form
3. Navigate to the submission page, the secondary contact information now shows DISPLAY ERROR

Screenshots:

![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/4fc8ed83-602f-413c-991c-aec67442d1db
)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by dleard** [comment]
This originates from the diff. DISPLAY ERROR is the last option in the chain of logic, so that's where to begin looking for this bug.

**Comment by LindsayMacfarlane** [comment]
Thank you Brianna! Tested in dev by:
1. creating a new project
2. editing an existing project

To confirm the user flow:
1. User adds a secondary contact to a project but doesn't add in any information.
2. User attempts to submit record but is unable to
3. In project task list, user sees "attention required"
4. User adds data or removed secondary contact
5. User can then submit project or project revision

Observation: It wasn't clear to me at first what the actual problem was, even after going back to the project contact page. It might be helpful to see a validation error displayed on the page under the empty secondary contact field. FYI @suhafa and @nanyangpro. This might be something to consider and do some testing on with the CIF team.
